version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
#            - postgres
            - redis
    celery:
        build: .
        command: celery -A manan worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
#    postgres:
#        image: postgres
#        container_name: postgres
#        environment:
#            - POSTGRES_DB=postgres
#            - POSTGRES_USER=sanyam
#            - POSTGRES_PASSWORD=sanyam
#        ports:
#            - "5431:5431"
#        volumes:
#            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
        
#volumes:
#    pgdata:

